name: Build and deploy to server

on:
  push:
    branches: ["feat/support-mermaid"]
    paths-ignore:
      - ".github/**"
      - ".docs/**"
  workflow_dispatch:
concurrency: ci-prod

jobs:
  build:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    name: Build website
    steps:
      - name: Maximize build space
        run: |
            df -h
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /opt/hostedtoolcache/CodeQL
            sudo docker image prune --all --force
            sudo docker builder prune -a
            df -h

      - uses: actions/checkout@v3
        with:
          ref: "master"
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Update submodule
        id: submodule
        run: |
          git submodule init
          git submodule update --remote
          cd docs
          git checkout main
          cd ..
          echo "submodule_sha=$(git submodule status | awk '{print $1}' | sed -r 's/[+-]+//g')" >> $GITHUB_OUTPUT
          echo "submodule_status=$(git submodule status)" >> $GITHUB_OUTPUT
          echo "git_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "build_date=$(date)" >> $GITHUB_OUTPUT

      - name: Install deps
        run: |
          yarn
          df -h

      - name: Clean up temporary files
        run: |
          sudo rm -rf /tmp/*
          sudo rm -rf /home/runner/work/_temp/*

      - name: Build website
        id: build-website
        env:
          CI: true
        run: |
          yarn build
